# @see http://eslint.org/docs/2.0.0/user-guide/configuring

root: true

extends:
    - plugin:import/errors
    - plugin:import/warnings


env:
    node: true

ignorePatterns:
    - dist

parserOptions:
    ecmaVersion: 2017
    sourceType: module
    ecmaFeatures:
        spread: true
        experimentalObjectRestSpread: true

globals:
    module: false
    exports: true
    node: true
    browser: true
    $tw: true
    $TPouch: true
    PouchDB: true

rules:
    prefer-template: ['error']
    semi: 1 # require semicolons
    no-unused-vars: ['error']
    valid-jsdoc: ['error']
    quotes: [ 1, 'single' ]
    indent: [ 1, 4 ] # 2-space indentation
    keyword-spacing: 1 # space before and after
    array-bracket-spacing: [1, 'always']  # enforce spaces inside of brackets
    prefer-const: ['error']
