# @see http://eslint.org/docs/user-guide/configuring

root: true
plugins:
    - import

env:
    node: true
    browser: true

ignorePatterns:
    - dist

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        spread: true

globals:
    module: false
    exports: true
    node: true
    browser: true
    $tw: true
    $TPouch: true
    PouchDB: true

settings:
    import/resolver:
        babel-module:
            root: ./src/**
            alias:
                "@plugin": ./src/plugins/danielo515/tiddlypouch

rules:
    import/no-unresolved: [2, { commonjs: true }]
    prefer-template: ['error']
    semi: 1 # require semicolons
    no-unused-vars: ['error']
    valid-jsdoc: ['error']
    quotes: [ 1, 'single' ]
    indent: [ 1, 4 ] # 2-space indentation
    keyword-spacing: 1 # space before and after
    array-bracket-spacing: [1, 'always']  # enforce spaces inside of brackets
    prefer-const: ['error']
